#!/usr/bin/env python3
"""
Parse shadcn/ui's `apps/v4/registry/themes.ts` and emit a Godot data file,
`addons/shadcn/palettes.gd`, holding every color palette as sRGB `Color`s.

shadcn has two axes:
  * BASE colors  (neutral, stone, zinc, mauve, olive, mist, taupe) — full palettes
  * ACCENT colors (blue, green, rose, ...) — override primary/secondary only

OKLCH -> sRGB conversion is done by tools/oklch.py (Godot uses sRGB).

Run:  python3 tools/generate_palettes.py
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from oklch import oklch_to_srgb  # noqa: E402

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(HERE, "tools", "themes.ts")
OUT = os.path.join(HERE, "addons", "shadcn", "palettes.gd")

BASE_NAMES = ["neutral", "stone", "zinc", "mauve", "olive", "mist", "taupe"]

# Keys we actually consume in the theme + components.
CHART_KEYS = ["chart_1", "chart_2", "chart_3", "chart_4", "chart_5"]
BASE_KEYS = [
    "background", "foreground", "card", "card_foreground", "popover",
    "popover_foreground", "primary", "primary_foreground", "secondary",
    "secondary_foreground", "muted", "muted_foreground", "accent",
    "accent_foreground", "destructive", "border", "input", "ring",
] + CHART_KEYS
ACCENT_KEYS = ["primary", "primary_foreground", "secondary",
               "secondary_foreground"] + CHART_KEYS


def parse_oklch(s):
    s = s.strip()
    assert s.startswith("oklch(") and s.endswith(")"), s
    body = s[6:-1]
    alpha = 1.0
    if "/" in body:
        body, a = body.split("/")
        a = a.strip()
        alpha = float(a.rstrip("%")) / 100 if a.endswith("%") else float(a)
    parts = body.split()
    L = float(parts[0].rstrip("%")) / (100 if parts[0].endswith("%") else 1)
    C = float(parts[1]) if len(parts) > 1 else 0.0
    h = float(parts[2]) if len(parts) > 2 else 0.0
    return oklch_to_srgb(L, C, h, alpha)


def color_str(t):
    return "Color(%.5g, %.5g, %.5g, %.5g)" % t


def parse_themes(text):
    """Return {name: {"light": {key: oklchstr}, "dark": {...}}}."""
    themes = {}
    # split into blocks beginning at each top-level `name: "X"`
    blocks = re.split(r'\n    name: "', text)
    for blk in blocks[1:]:
        name = blk[: blk.index('"')]
        out = {"light": {}, "dark": {}}
        for mode in ("light", "dark"):
            m = re.search(mode + r":\s*\{(.*?)\n      \},", blk, re.DOTALL)
            if not m:
                continue
            for km in re.finditer(r'"?([a-zA-Z0-9-]+)"?:\s*"(oklch\([^"]*\))"', m.group(1)):
                key = km.group(1).replace("-", "_")
                out[mode][key] = km.group(2)
        themes[name] = out
    return themes


def build():
    with open(SRC) as f:
        themes = parse_themes(f.read())

    base = {}
    for name in BASE_NAMES:
        t = themes[name]
        entry = {"light": {}, "dark": {}}
        for mode in ("light", "dark"):
            src = t[mode]
            for k in BASE_KEYS:
                if k in src:
                    entry[mode][k] = parse_oklch(src[k])
            # Derived tokens not present in themes.ts (they live in globals.css).
            fg = entry[mode]["foreground"]
            bg = entry[mode]["background"]
            entry[mode]["destructive_foreground"] = (1, 1, 1, 1)
            entry[mode]["selection"] = fg
            entry[mode]["selection_foreground"] = bg
        base[name] = entry

    accent = {}
    accent_names = []
    for name, t in themes.items():
        if name in BASE_NAMES:
            continue
        accent_names.append(name)
        entry = {"light": {}, "dark": {}}
        for mode in ("light", "dark"):
            for k in ACCENT_KEYS:
                if k in t[mode]:
                    entry[mode][k] = parse_oklch(t[mode][k])
        accent[name] = entry

    return base, accent, accent_names


def emit(base, accent, accent_names):
    lines = [
        "@tool",
        "class_name ShadcnPalettes",
        "extends RefCounted",
        "## AUTO-GENERATED by tools/generate_palettes.py from shadcn/ui themes.ts.",
        "## Do not edit by hand. All values are sRGB (Godot does not use OKLCH).",
        "",
        'const BASE_NAMES := ["%s"]' % '", "'.join(BASE_NAMES),
        'const ACCENT_NAMES := ["%s"]' % '", "'.join(accent_names),
        "",
        "const BASE := {",
    ]
    for name, entry in base.items():
        lines.append('\t"%s": {' % name)
        for mode in ("light", "dark"):
            pairs = ", ".join('"%s": %s' % (k, color_str(v)) for k, v in entry[mode].items())
            lines.append('\t\t"%s": {%s},' % (mode, pairs))
        lines.append("\t},")
    lines.append("}")
    lines.append("")
    lines.append("const ACCENT := {")
    for name, entry in accent.items():
        lines.append('\t"%s": {' % name)
        for mode in ("light", "dark"):
            pairs = ", ".join('"%s": %s' % (k, color_str(v)) for k, v in entry[mode].items())
            lines.append('\t\t"%s": {%s},' % (mode, pairs))
        lines.append("\t},")
    lines.append("}")
    lines.append("")
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print("wrote", OUT, "(%d base, %d accent)" % (len(base), len(accent)))


if __name__ == "__main__":
    b, a, names = build()
    emit(b, a, names)
